#!/bin/bash
run_brew() {
  if has "brew"; then
    echo "$(tput setaf 2)Already installed Homebrew ✔︎$(tput sgr0)"
  else
    echo "Installing Homebrew..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if has "brew"; then
    echo "Updating Homebrew..."
    brew upgrade
    [[ $? ]] && echo "$(tput setaf 2)Update Homebrew complete. ✔︎$(tput sgr0)"

    local list_formulae
    local -a missing_formulae
    local -a desired_formulae=(
      # 'ab'
      'autoconf'
      'automake'
      'awscli'
      # 'android-sdk'
      'ansible'
      'anyenv'
      'asciinema'
      'cocoapods'
      'composer'
      'coreutils'
      'ctags'
      'direnv'
      'docker-compose'
      'git-delta'
      # 'dart'
      'fontforge'
      'gcc'
      'gettext'
      'gibo'
      'git'
      'gpg'
      # 'httpd22'
      'ideviceinstaller'
      'imagemagick'
      'ios-deploy'
      'iproute2mac'
      'jq'
      'libimobiledevice'
      'mysql'
      'nkf'
      'neovim'
      'openssl'
      'packer'
      'peco'
      'postgresql'
      'qt'
      'sqlite'
      'svn'
      'the_platinum_searcher'
      'tmux'
      'tmux-xpanes'
      'unar'
      'tig'
      'tree'
      'w3m'
      'wget'
      'yarn'
      'youtube-dl'
      'zsh'
    )

    local installed=`brew list --formula`

    for index in ${!desired_formulae[*]}
    do
      local formula=`echo ${desired_formulae[$index]} | cut -d' ' -f 1`
      if [[ -z `echo "${installed}" | grep "^${formula}$"` ]]; then
        missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
      else
        echo "Installed ${formula}"
      fi
    done

    if [[ "$missing_formulae" ]]; then
      list_formulae=$( printf "%s " "${missing_formulae[@]}" )

      echo "Installing missing Homebrew formulae..."
      brew install $list_formulae

      [[ $? ]] && echo "$(tput setaf 2)Installed missing formulae ✔︎$(tput sgr0)"
    fi

    ln -sfv /usr/local/opt/mysql/*.plist ~/Library/LaunchAgents
    ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents

    local -a missing_formulae=()
    local -a desired_formulae=(
      'dropbox'
      'firefox'
      'google-chrome'
      'google-backup-and-sync'
      'skitch'
      '1password'
      'visual-studio-code'
      'xquartz'
    )
    # cask
    local installed=`brew list --cask`

    for index in ${!desired_formulae[*]}
    do
      local formula=`echo ${desired_formulae[$index]} | cut -d' ' -f 1`
      if [[ -z `echo "${installed}" | grep "^${formula}$"` ]]; then
        missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
      else
        echo "Installed ${formula}"
      fi
    done

    if [[ "$missing_formulae" ]]; then
      list_formulae=$( printf "%s " "${missing_formulae[@]}" )

      echo "Installing missing Homebrew formulae..."
      brew install --cask $list_formulae

      [[ $? ]] && echo "$(tput setaf 2)Installed missing formulae ✔︎$(tput sgr0)"
    fi

    echo "Cleanup Homebrew..."
    brew cleanup
    echo "$(tput setaf 2)Cleanup Homebrew complete. ✔︎$(tput sgr0)"
  fi
}
