#!/bin/bash
run_brew() {
  if has "brew"; then
    echo "$(tput setaf 2)Already installed Homebrew ✔︎$(tput sgr0)"
  else
    echo "Installing Homebrew..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if has "brew"; then
    echo "Updating Homebrew..."
    brew update && brew upgrade
    [[ $? ]] && echo "$(tput setaf 2)Update Homebrew complete. ✔︎$(tput sgr0)"

    brew tap 'caskroom/cask'
    # brew tap 'homebrew/apache'
    # brew tap 'homebrew/dupes'
    brew tap 'sanemat/font'
    # brew tap 'homebrew/php'
    brew tap 'greymd/tools'

    local list_formulae
    local -a missing_formulae
    local -a desired_formulae=(
      # 'ab'
      'autoconf'
      'automake'
      'awscli'
      # 'android-sdk'
      'ansible'
      'asciinema'
      'cocoapods'
      'composer'
      'coreutils'
      'ctags'
      # 'dart'
      'ffmpeg'
      'fontforge'
      'gcc'
      'gettext'
      'gibo'
      'git'
      'gpg'
      # 'httpd22'
      'ideviceinstaller'
      'imagemagick'
      'ios-deploy'
      'iproute2mac'
      'jq'
      'libimobiledevice'
      'mysql'
      'nkf'
      'neovim'
      'openssl'
      'packer'
      'peco'
      'postgresql'
      'qt'
      's3cmd'
      'sqlite'
      'svn'
      'the_platinum_searcher'
      'tmux'
      'tmux-xpanes'
      'unar'
      'tree'
      'wget'
      'yarn'
      'youtube-dl'
      'zsh'
    )

    local installed=`brew list`

    for index in ${!desired_formulae[*]}
    do
      local formula=`echo ${desired_formulae[$index]} | cut -d' ' -f 1`
      if [[ -z `echo "${installed}" | grep "^${formula}$"` ]]; then
        missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
      else
        echo "Installed ${formula}"
        [[ "${formula}" = "ricty" ]] && local installed_ricty=true
      fi
    done

    if [[ "$missing_formulae" ]]; then
      list_formulae=$( printf "%s " "${missing_formulae[@]}" )

      echo "Installing missing Homebrew formulae..."
      brew install $list_formulae

      [[ $? ]] && echo "$(tput setaf 2)Installed missing formulae ✔︎$(tput sgr0)"
    fi

    ln -sfv /usr/local/opt/mysql/*.plist ~/Library/LaunchAgents
    ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents
    if [ -z "${installed_ricty}"  ]; then
      echo "Reload fonts. This could take a while..."
      local cellar=`brew --config | grep 'HOMEBREW_CELLAR' | cut -d' ' -f 2`
      find ${cellar}/ricty/*/share/fonts/Ricty*.ttf | xargs -I % cp % ~/Library/Fonts
      fc-cache -vf
    fi

    local -a missing_formulae=()
    local -a desired_formulae=(
      'alfred'
      'dash'
      'dashlane'
      'dropbox'
      'firefox'
      'franz'
      'google-chrome'
      # 'google-drive'
      'skitch'
      'vagrant'
      'virtualbox'
      'visual-studio-code'
      'xquartz'
    )
    # cask
    local installed=`brew cask list`

    for index in ${!desired_formulae[*]}
    do
      local formula=`echo ${desired_formulae[$index]} | cut -d' ' -f 1`
      if [[ -z `echo "${installed}" | grep "^${formula}$"` ]]; then
        missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
      else
        echo "Installed ${formula}"
      fi
    done

    pod setup

    if [[ "$missing_formulae" ]]; then
      list_formulae=$( printf "%s " "${missing_formulae[@]}" )

      echo "Installing missing Homebrew formulae..."
      brew cask install $list_formulae

      [[ $? ]] && echo "$(tput setaf 2)Installed missing formulae ✔︎$(tput sgr0)"
    fi

    echo "Cleanup Homebrew..."
    brew cleanup
    echo "$(tput setaf 2)Cleanup Homebrew complete. ✔︎$(tput sgr0)"
  fi
}
