#!/bin/bash
run_go() {
  if has "go"; then
    echo "Install go packages..."

    go install golang.org/x/tools/gopls@latest
    go install golang.org/x/tools/cmd/goimports@latest
    go install github.com/boyter/cs@latest

    echo "$(tput setaf 2)Install go packages complete. ✔︎$(tput sgr0)"
  fi
}
