#!/bin/bash
run_go() {
  if has "go"; then
    echo "Install go packages..."

    go get -u github.com/motemen/ghq
    go get -u golang.org/x/tools/gopls
    go get -u golang.org/x/tools/cmd/goimports

    if [[ $OSTYPE =~ "linux" ]]; then
      cd $HOME/dev/src/github.com/peco/peco
      go build cmd/peco/peco.go
      mv peco $HOME/dev/bin/
      cd ${DOT_DIRECTORY}
    fi

    echo "$(tput setaf 2)Install go packages complete. ✔︎$(tput sgr0)"
  fi
}
