#!/bin/bash
run_node() {
  if has "npm"; then
    echo "Install npm packages..."

    npm install -g \
      eslint \
      github-copilot-cli \
      http-server \
      node-google-apps-script \
      prettier \
      pretty-js \
      tern \
      tldr \
      tldr \
      tslint \
      tsserver \
      typescript \
      typings \
      uglify-js \
      uglifycss

    echo "$(tput setaf 2)Install npm packages complete. ✔︎$(tput sgr0)"
  fi
}
