#!/bin/bash
run_yarn() {
  if has "yarn"; then
    echo "Install yarn packages..."

    yarn global add node-gyp \
     coffeescript \
     eslint \
     eslint-config-vue \
     eslint-plugin-html \
     eslint-plugin-vue \
     http-server \
     node-google-apps-script \
     prettier \
     tern \
     tldr \
     tslint \
     typescript \
     typings \
     uglify-js \
     uglifycss

    echo "$(tput setaf 2)Install go packages complete. ✔︎$(tput sgr0)"
  fi
}
